### ISSUE TITLE
Server does not accept 'content-type: application/json; charset=utf-8'

### ISSUE THREAD

**Issue by gschmottlach-xse** [sangaman/http-jsonrpc-server#1]
I tried calling a method on your server implementation using another popular JSON-RPC package (https://github.com/tedeh/jayson) but it appears your implementation is a little *too* strict on the 'content-type' header. Your code is explicitly looking for 'application/json' but other JSON-RPC packages tend to send 'application/json; charset=utf-8" in the 'content-type' of their JSON-RPC POST requests.

The culprit is line 34 in reqhandler.js:

`
 } else if (req.headers['content-type'] !== 'application/json') {
`

A simple fix might be:

`
} else if (req.headers['content-type'].search('application\/json') === -1) {
`

I hope you could relax your 'content-type' checking so it will ignore 'charset=utf-8' in your validation logic.

Thanks for making your library available . . .

**Comment by gschmottlach-xse** [comment]
Thanks for making this change! I look forward to taking advantage of it when you update your npm module.

**Comment by sangaman** [comment]
Published, thanks and please let me know if you come up with any more feedback!

**Comment by gschmottlach-xse** [comment]
Thanks for the timely update . . .

With respect to feedback, have you ever considered a mechanism to associate a "context" with the server methods? Often the JSON-RPC handlers/functions are methods of a larger class. Right now I have to individually "bind" the 'this' reference to each function. Wonder if you've considered having a context argument as an option in the constructor that you can assign the methods. This would allow you to *apply* the context to the message handler when called. I think I've seen other JSON-RPC servers provide a similar feature.

**Comment by sangaman** [comment]
Yes I'll look into that, thanks.
