### ISSUE TITLE
It's possible to make it work with https?

### ISSUE THREAD

**Issue by fabiodcorreia** [sangaman/http-jsonrpc-server#12]
I have a use case where I need to mock a JSON RPC server but it needs to be in HTTPS even for development. It's possible to make it work with https without using a reverse proxy like nginx?

Thanks

**Comment by sangaman** [comment]
Hi, sorry I didn't get to this earlier and I noticed you just closed it. This should be possible with some modifications and manually providing a certificate and key to the server, if this is still something you need let me know and I'll see if I can extend that functionality here.

**Comment by fabiodcorreia** [comment]
No worry, I closed it because at the end I didn't used JSON RPC so I will not need to mock it. Thanks for asking :)
