### ISSUE TITLE
EventEmitter memory leak when cycling between listen()/close() repeatedly

### ISSUE THREAD

**Issue by gschmottlach-xse** [sangaman/http-jsonrpc-server#3]
I created a JSON-RPC Server instance and cycled between calls to *Server.listen()* and *Server.close()*. After about four iterations I get the dreaded

`
(node:9327) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
`

Looking at the *listen()/close()* methods in http-jsonrpc-server.js I see that there are calls to once('error') on the underlying HTTP server where you catch any errors. The problem, of course, is that if there are **no** errors those anonymous event listeners will never be removed.  My suggestion is to remove **all** the anonymous *error* listeners when the server is closed (either successfully or if an error event is received), .e.g.

`
  close() {
    return new Promise((resolve, reject) => {
      this.server.close(() => {
        this.server.removeAllListeners('error');
        resolve(true);
      }).once('error', (err) => {
        this.server.removeAllListeners('error');
        reject(err);
      });
    });
  }
`

You have to call removeAllListeners() in **both** spots since there is also an anonymous listener that is installed by the call to *listen()* that needs to be cleaned up as well.  I made this change and the leaky events disappeared.

**Comment by sangaman** [comment]
I was able to recreate the error in a test case, and I added lines to remove these listeners and make the test case pass in #5. Thanks for catching this, it was just an oversight on my part. Definitely let me now if you've encountered anything else and if you've implemented any fixes/enhancements that are working feel free to open a PR.

**Comment by gschmottlach-xse** [comment]
Thanks for quickly addressing this corner-case. It can be tough to catch them all since this issue wasn't one that was glaringly apparent. I only realized it after thinking about it a bit. Looking forward to seeing it updated in the NPM module.
