### ISSUE TITLE
Set auth to a server with http-jsonrpc-server 

### ISSUE THREAD

**Issue by aitoribanez** [sangaman/http-jsonrpc-server#6]
Hello Daniel,
  
   ¿Is there a way to set an authentication, user/pass for example on a server with http-jsonrpc-server?

Thank you very much! :-D

**Comment by sangaman** [comment]
Hi Aitor! Not currently, authentication wasn't a priority for me but it's been on my mind and I was waiting to see if someone would ask for it. I can certainly implement [Basic Authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) soon, but on its own that is not very secure without TLS, at least when facing the public internet. Supporting HTTPS would be desirable too but implementing that (or some more sophisticated authentication scheme) would be a bigger effort.

Would Basic Authentication work for you? At least for now?

**Comment by aitoribanez** [comment]
Hello Daniel! 

   Thanks for the quick answer.
   Basic Authentication would work me. 

Thanks! :-D

**Comment by sangaman** [comment]
Cool! Should have it ready in a few days.
